spring.application.name=citasPeluqueria

# Conexión a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=husna
spring.datasource.password=husna

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialecto de Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Creación/actualización automática del esquema
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en consola
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Inicialización de datos SQL
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# JWT Configuration
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=86400000